Allow WebDAV authentication with non JWT tokens
pulsejet/nextcloud-oidc-login pull request #123
Opened 2021-10-06 17:26 UTC by azmeuk

Hi. I have this setup:
- [canaille](https://gitlab.com/yaal/canaille) as my identity provider
- nextcloud + nextcloud-oidc-login as my resource server for carddav contacts
- roundcube + [rcmcarddav](https://github.com/mstilkerich/rcmcarddav) as my OIDC client, that wants to access the carddav contacts

As discussed in [this bug report](https://github.com/mstilkerich/rcmcarddav/issues/354) it seems that identity providers like Keycloak provide JWT access tokens, although it is not required by the specifications. nextcloud-oidc-login expects access token to be JWT but some providers like canaille do not provide JWT access token, but regular ones.

This patch allows WebDAV authentication with a regular access token. When a non-JWT token is detected (not dot in the string) requests are made on the identity provider introspection endpoint and userinfo endpoint to collect information that would have been in the token if it was a JWT.

2021-10-18 07:12 UTC, azmeuk commented
@sirkrypt0 Does it seem OK to you now?

2021-10-30 16:15 UTC, azmeuk commented
@sirkrypt0 gentle ping :pray:

2021-11-08 15:46 UTC, azmeuk commented
@sirkrypt0 @pulsejet would you have some time soon to review this patch?
I am sorry to insist, and I am very aware that you must be busy on higher priority things. I think this can be a very quick review.

2021-11-14 17:01 UTC, sirkrypt0 requested changes
I now tested it, but wasn't as quick of a review as expected. The JWT part initially did not work as the `base64_decode` function couldn't be found.

2021-11-15 15:41 UTC, azmeuk commented on lib/Provider/OpenIDConnectClient.php
> +                $joseHeader = json_decode(base64url_decode($parts[0]));
This is strange. I think it worked for me, maybe I forgot to commit a `use` statement?

2021-11-15 15:43 UTC, azmeuk commented on lib/Provider/OpenIDConnectClient.php
> +                json_decode(base64url_decode($parts[1]));
The ` JSON_THROW_ON_ERROR` was introduced with php 7.3 so maybe the latter option is safer?

2021-11-15 15:46 UTC, azmeuk commented
Thank you very much for your review! Everything is fixed now.

2021-11-23 12:41 UTC, azmeuk commented
@sirkrypt0: I had an email chat with @pulsejet, he does not have time anymore to maintain the project and agrees to share the repository with contributors. Would you be interested?

2021-11-26 20:31 UTC, sirkrypt0 commented
> @sirkrypt0: I had an email chat with @pulsejet, he does not have time anymore to maintain the project and agrees to share the repository with contributors. Would you be interested?

@azmeuk I am (replied on Twitter as well)

2021-11-29 15:58 UTC, merged